[2025-04-16T15:24:31.253+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:24:31.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:24:31.874+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:24:31.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:25:02.101+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:25:01.978+0000] {timeout.py:68} ERROR - Process timed out, PID: 113
[2025-04-16T15:25:02.220+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:25:02.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/window/ewm.py", line 26, in <module>
    from pandas.core.util.numba_ import (
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1532, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1506, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1624, in find_spec
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 113
[2025-04-16T15:25:02.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:25:02.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 31.715 seconds
[2025-04-16T15:25:35.100+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:25:35.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:25:35.128+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:25:35.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:25:46.911+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:25:47.965+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:25:47.964+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T15:25:48.007+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:25:48.007+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T15:25:48.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 13.016 seconds
[2025-04-16T15:26:18.742+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:26:18.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:26:18.772+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:26:18.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:26:40.869+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:26:42.129+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:26:42.084+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T15:26:42.593+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:26:42.571+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T15:26:42.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 24.251 seconds
[2025-04-16T15:27:17.517+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:27:17.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:27:17.806+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:27:17.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:27:48.258+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:27:48.022+0000] {timeout.py:68} ERROR - Process timed out, PID: 158
[2025-04-16T15:27:48.708+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:27:48.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 12, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 757, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 158
[2025-04-16T15:27:48.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:27:49.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 32.237 seconds
[2025-04-16T15:29:38.939+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:29:39.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:29:39.505+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:29:39.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:31:15.650+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:31:15.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:31:15.721+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:31:15.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:31:36.223+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:31:39.088+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:31:39.081+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T15:31:39.217+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:31:39.216+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T15:31:39.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 23.837 seconds
[2025-04-16T15:32:10.802+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:32:10.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:32:10.848+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:32:10.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:32:42.257+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:32:41.149+0000] {timeout.py:68} ERROR - Process timed out, PID: 220
[2025-04-16T15:32:51.291+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:32:42.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 118, in <module>
    from pandas.core.reshape.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/api.py", line 11, in <module>
    from pandas.core.reshape.merge import (
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 757, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 220
[2025-04-16T15:33:01.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:33:34.465+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:33:34.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:33:34.705+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:33:34.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:47:38.849+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:47:39.198+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:47:39.795+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:47:39.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:51:14.253+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:51:15.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:51:21.911+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:51:18.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:52:11.168+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:52:09.684+0000] {timeout.py:68} ERROR - Process timed out, PID: 241
[2025-04-16T15:52:17.499+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:52:13.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1532, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1506, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1624, in find_spec
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 241
[2025-04-16T15:52:19.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:52:40.776+0000] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 928, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 648, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(ParseImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-16T15:53:30.705+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:53:31.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:53:34.086+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:53:32.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:56:38.995+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:56:39.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:56:39.408+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:56:39.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:57:10.451+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:57:09.828+0000] {timeout.py:68} ERROR - Process timed out, PID: 263
[2025-04-16T15:57:11.815+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:57:10.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/window/ewm.py", line 49, in <module>
    from pandas.core.window.rolling import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/window/rolling.py", line 48, in <module>
    from pandas.core._numba import executor
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/_numba/executor.py", line 73, in <module>
    np.dtype("int32"): np.int64,
    ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 263
[2025-04-16T15:57:12.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:57:13.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 34.889 seconds
[2025-04-16T15:57:52.862+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T15:57:52.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T15:57:52.926+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:57:52.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:57:59.941+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T15:58:03.033+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:58:03.019+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T15:58:03.465+0000] {logging_mixin.py:190} INFO - [2025-04-16T15:58:03.463+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T15:58:04.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 11.615 seconds
[2025-04-16T16:02:18.110+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:02:18.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:02:18.338+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:02:18.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:02:31.013+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:02:31.081+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:02:31.081+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:02:31.112+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:02:31.111+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:02:31.143+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 13.269 seconds
[2025-04-16T16:03:03.117+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:03:03.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:03:03.160+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:03:03.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:03:33.850+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:03:33.212+0000] {timeout.py:68} ERROR - Process timed out, PID: 113
[2025-04-16T16:03:33.989+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:03:33.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 11, in <module>
    from minio import Minio
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/__init__.py", line 45, in <module>
    from .minioadmin import MinioAdmin as MinioAdmin
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/minioadmin.py", line 44, in <module>
    from .crypto import decrypt, encrypt
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/crypto.py", line 24, in <module>
    from Crypto.Cipher import AES, ChaCha20_Poly1305
  File "/home/airflow/.local/lib/python3.12/site-packages/Crypto/Cipher/ChaCha20_Poly1305.py", line 35, in <module>
    from Crypto.Hash import Poly1305, BLAKE2s
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1532, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1506, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1638, in find_spec
  File "<frozen importlib._bootstrap_external>", line 161, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 153, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 113
[2025-04-16T16:03:34.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:03:35.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 32.031 seconds
[2025-04-16T16:04:08.443+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:04:08.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:04:08.568+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:04:08.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:04:38.934+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:04:38.928+0000] {timeout.py:68} ERROR - Process timed out, PID: 130
[2025-04-16T16:04:38.976+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:04:38.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 52, in <module>
    from pandas.core.arrays._arrow_string_mixins import ArrowStringArrayMixin
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/_arrow_string_mixins.py", line 11, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "pyarrow/_compute.pyx", line 1513, in init pyarrow._compute
  File "pyarrow/_compute.pyx", line 837, in pyarrow._compute._min_count_doc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 130
[2025-04-16T16:04:38.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:04:39.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 31.580 seconds
[2025-04-16T16:05:10.366+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:10.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:05:10.377+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:10.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:16.103+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:16.803+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:16.801+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:05:16.833+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:16.832+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:05:16.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 6.533 seconds
[2025-04-16T16:05:47.523+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:47.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:05:47.561+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:47.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:51.192+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:05:51.247+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:51.246+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:05:51.287+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:05:51.287+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:05:51.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 3.919 seconds
[2025-04-16T16:06:22.216+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:06:22.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:06:22.247+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:06:22.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:06:34.755+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:06:34.884+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:06:34.882+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:06:34.953+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:06:34.953+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:06:35.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 12.981 seconds
[2025-04-16T16:07:05.491+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:05.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:07:05.497+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:05.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:06.417+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:06.455+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:06.455+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:07:06.481+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:06.480+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:07:06.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.033 seconds
[2025-04-16T16:07:36.902+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:36.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:07:36.908+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:36.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:37.715+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:07:37.761+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:37.761+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:07:37.784+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:07:37.783+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:07:37.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 0.926 seconds
[2025-04-16T16:08:09.047+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:09.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:08:09.060+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:09.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:12.738+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:12.986+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:12.978+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:08:13.044+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:13.043+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:08:13.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 4.126 seconds
[2025-04-16T16:08:43.737+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:43.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:08:43.745+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:43.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:56.174+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:08:57.770+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:57.709+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:08:57.933+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:08:57.932+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:08:58.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 14.458 seconds
[2025-04-16T16:09:29.125+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:09:29.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:09:29.136+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:09:29.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:09:31.599+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:09:31.752+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:09:31.751+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:09:31.793+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:09:31.793+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:09:31.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 2.758 seconds
[2025-04-16T16:10:02.796+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:10:02.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:10:02.804+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:10:02.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:10:05.255+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:10:05.405+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:10:05.404+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:10:05.449+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:10:05.448+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:10:05.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 2.718 seconds
[2025-04-16T16:12:37.616+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:12:38.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:12:38.435+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:12:38.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:13:12.865+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:13:12.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:13:12.877+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:13:12.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:13:22.846+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:16:18.917+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:16:18.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:16:18.961+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:16:18.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:16:30.381+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:16:32.714+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:16:32.688+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:16:32.987+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:16:32.986+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:16:33.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 14.778 seconds
[2025-04-16T16:17:05.550+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:05.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:17:05.625+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:05.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:14.583+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:14.792+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:14.789+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:17:14.849+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:14.848+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:17:14.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 9.524 seconds
[2025-04-16T16:17:45.902+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:45.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:17:45.912+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:45.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:48.979+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:17:49.176+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:49.175+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:17:49.228+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:17:49.227+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:17:49.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 3.435 seconds
[2025-04-16T16:18:19.989+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:19.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:18:19.998+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:19.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:22.153+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:22.263+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:22.261+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:18:22.325+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:22.324+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:18:22.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 2.446 seconds
[2025-04-16T16:18:52.901+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:52.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:18:52.908+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:52.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:54.144+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:18:54.217+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:54.216+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:18:54.241+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:18:54.240+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:18:54.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.380 seconds
[2025-04-16T16:19:24.910+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:24.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:19:24.917+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:24.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:26.575+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:26.695+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:26.694+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:19:26.744+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:26.743+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:19:26.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.902 seconds
[2025-04-16T16:19:57.243+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:57.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:19:57.253+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:57.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:58.672+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:19:58.740+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:58.739+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:19:58.768+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:19:58.767+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:19:58.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.578 seconds
[2025-04-16T16:20:30.909+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:20:31.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:20:31.439+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:20:31.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:20:44.591+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:20:45.081+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:20:45.058+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:20:45.437+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:20:45.395+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:20:45.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 16.489 seconds
[2025-04-16T16:21:16.379+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:16.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:21:16.390+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:16.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:17.944+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:18.027+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:18.026+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:21:18.058+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:18.058+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:21:18.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.737 seconds
[2025-04-16T16:21:48.394+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:48.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:21:48.407+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:48.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:51.948+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:21:53.027+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:53.007+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:21:53.316+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:21:53.315+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:21:53.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 5.105 seconds
[2025-04-16T16:22:23.994+0000] {processor.py:186} INFO - Started process (PID=369) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:22:23.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:22:24.011+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:22:24.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:22:29.205+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:22:29.745+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:22:29.725+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:22:29.893+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:22:29.885+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:22:29.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 5.999 seconds
[2025-04-16T16:23:00.808+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:00.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:23:00.819+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:00.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:02.736+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:02.863+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:02.860+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:23:02.899+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:02.898+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:23:02.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 2.151 seconds
[2025-04-16T16:23:33.536+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:33.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:23:33.546+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:33.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:35.169+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:23:35.252+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:35.251+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:23:35.299+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:23:35.298+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:23:35.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 1.829 seconds
[2025-04-16T16:31:39.111+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:31:39.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:31:39.125+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:39.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:31:56.644+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:31:58.351+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.346+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:weather_pipeline
[2025-04-16T16:31:58.709+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.697+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:weather_pipeline
[2025-04-16T16:31:58.794+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.791+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:weather_pipeline
[2025-04-16T16:31:58.837+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.836+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:weather_pipeline
[2025-04-16T16:31:58.870+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.869+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:weather_pipeline
[2025-04-16T16:31:58.945+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:58.944+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:weather_pipeline
[2025-04-16T16:31:59.007+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:59.006+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:weather_pipeline
[2025-04-16T16:31:59.015+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:59.011+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:31:59.154+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:59.152+0000] {dag.py:3262} INFO - Creating ORM DAG for weather_pipeline
[2025-04-16T16:31:59.162+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:31:59.161+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:31:59.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 20.336 seconds
[2025-04-16T16:32:32.158+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:32:32.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:32:32.526+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:32:32.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:33:02.627+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:33:02.620+0000] {timeout.py:68} ERROR - Process timed out, PID: 118
[2025-04-16T16:33:02.660+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:33:02.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 118, in <module>
    from pandas.core.reshape.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/api.py", line 2, in <module>
    from pandas.core.reshape.encoding import (
  File "<frozen importlib._bootstrap>", line 1357, in _find_and_load
  File "<frozen importlib._bootstrap>", line 418, in __enter__
  File "<frozen importlib._bootstrap>", line 311, in acquire
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 132, in setdefault
  File "<frozen importlib._bootstrap>", line 80, in __init__
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 118
[2025-04-16T16:33:02.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:33:02.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 30.818 seconds
[2025-04-16T16:33:34.761+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:33:34.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:33:35.778+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:33:35.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:34:19.742+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:34:19.739+0000] {timeout.py:68} ERROR - Process timed out, PID: 135
[2025-04-16T16:34:19.746+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f9cb6f8d080>
[2025-04-16T16:34:19.749+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-04-16T16:34:19.752+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-04-16T16:34:19.761+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-04-16T16:34:19.764+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2025-04-16T16:34:19.769+0000] {logging_mixin.py:190} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2025-04-16T16:34:19.775+0000] {logging_mixin.py:190} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 135
[2025-04-16T16:35:06.393+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:35:06.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:35:06.724+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:35:06.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:36:21.015+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:36:21.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:36:21.085+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:36:21.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:36:55.716+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:36:55.712+0000] {timeout.py:68} ERROR - Process timed out, PID: 169
[2025-04-16T16:36:55.729+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f9cb6f8d080>
[2025-04-16T16:36:55.745+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-04-16T16:36:55.753+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-04-16T16:36:55.768+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-04-16T16:36:55.774+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2025-04-16T16:36:55.787+0000] {logging_mixin.py:190} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2025-04-16T16:36:55.796+0000] {logging_mixin.py:190} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 169
[2025-04-16T16:37:40.697+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:37:41.151+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:37:41.640+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:37:41.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:38:27.230+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:38:26.976+0000] {timeout.py:68} ERROR - Process timed out, PID: 186
[2025-04-16T16:38:27.676+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:38:27.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 645, in parent
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 186
[2025-04-16T16:38:27.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:53:14.478+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:53:14.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:53:14.500+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:53:14.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:53:46.987+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:53:45.058+0000] {timeout.py:68} ERROR - Process timed out, PID: 59
[2025-04-16T16:53:47.479+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:53:47.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 11, in <module>
    from minio import Minio
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/__init__.py", line 45, in <module>
    from .minioadmin import MinioAdmin as MinioAdmin
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/minioadmin.py", line 54, in <module>
    class _COMMAND(Enum):
  File "/usr/local/lib/python3.12/enum.py", line 595, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 272, in __set_name__
    if not hasattr(enum_member, '_value_'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 59
Error calling __set_name__ on '_proto_member' instance 'SITE_REPLICATION_STATUS' in '_COMMAND'
[2025-04-16T16:53:47.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:53:49.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 34.827 seconds
[2025-04-16T16:54:24.510+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:54:24.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:54:24.770+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:54:24.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:54:54.814+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:54:54.811+0000] {timeout.py:68} ERROR - Process timed out, PID: 80
[2025-04-16T16:54:54.818+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f70c2229080>
[2025-04-16T16:54:54.820+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-04-16T16:54:54.823+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-04-16T16:54:54.826+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-04-16T16:54:54.829+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2025-04-16T16:54:54.832+0000] {logging_mixin.py:190} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2025-04-16T16:54:54.834+0000] {logging_mixin.py:190} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 80
[2025-04-16T16:55:03.976+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:55:14.080+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:55:14.036+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:55:46.385+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:55:46.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:55:46.489+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:55:46.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:56:04.305+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:56:09.692+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:56:09.672+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:56:09.935+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:56:09.934+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:56:10.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 24.215 seconds
[2025-04-16T16:56:42.489+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:56:42.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:56:42.912+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:56:42.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:57:26.119+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:57:26.112+0000] {timeout.py:68} ERROR - Process timed out, PID: 116
[2025-04-16T16:57:26.123+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f70c2229080>
[2025-04-16T16:57:26.125+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-04-16T16:57:26.126+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-04-16T16:57:26.128+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-04-16T16:57:26.132+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2025-04-16T16:57:26.179+0000] {logging_mixin.py:190} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2025-04-16T16:57:26.181+0000] {logging_mixin.py:190} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 116
[2025-04-16T16:57:30.803+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:57:31.528+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:57:31.520+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:58:33.772+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:58:33.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:58:33.972+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:58:33.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:58:57.936+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:58:59.220+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:58:59.215+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:58:59.350+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:58:59.348+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:58:59.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 26.681 seconds
[2025-04-16T16:59:32.617+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T16:59:32.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T16:59:32.884+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:59:32.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:59:44.668+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T16:59:45.093+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:59:45.090+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T16:59:45.279+0000] {logging_mixin.py:190} INFO - [2025-04-16T16:59:45.279+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T16:59:45.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 13.552 seconds
[2025-04-16T17:00:21.851+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:00:21.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:00:22.022+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:00:22.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:00:40.729+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:00:41.929+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:00:41.898+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:00:42.306+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:00:42.305+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:00:42.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 20.835 seconds
[2025-04-16T17:01:13.474+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:01:13.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:01:13.489+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:01:13.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:01:23.037+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:01:23.600+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:01:23.597+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:01:23.755+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:01:23.754+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:01:23.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 10.507 seconds
[2025-04-16T17:01:58.303+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:01:58.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:01:58.339+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:01:58.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:02:17.564+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:02:17.909+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:02:17.906+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:02:18.624+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:02:18.623+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:02:23.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 25.660 seconds
[2025-04-16T17:02:54.713+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:02:54.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:02:54.735+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:02:54.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:03:08.784+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:03:10.595+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:03:10.575+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:03:11.177+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:03:11.177+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:03:12.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 17.560 seconds
[2025-04-16T17:03:45.161+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:03:45.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:03:45.354+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:03:45.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:04:16.464+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:04:15.425+0000] {timeout.py:68} ERROR - Process timed out, PID: 225
[2025-04-16T17:04:17.240+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:04:16.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 135, in <module>
    from pandas import api, arrays, errors, io, plotting, tseries
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/api/__init__.py", line 2, in <module>
    from pandas.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/api/typing/__init__.py", line 31, in <module>
    from pandas.io.json._json import JsonReader
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/__init__.py", line 1, in <module>
    from pandas.io.json._json import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 67, in <module>
    from pandas.io.parsers.readers import validate_integer
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 27, in <module>
    from pandas._libs.parsers import STR_NA_VALUES
  File "parsers.pyx", line 2089, in init pandas._libs.parsers
  File "parsers.pyx", line 2065, in pandas._libs.parsers._compute_na_values
  File "/home/airflow/.local/lib/python3.12/site-packages/numpy/core/getlimits.py", line 685, in __init__
    def __init__(self, int_type):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 225
[2025-04-16T17:04:17.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:04:20.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 36.290 seconds
[2025-04-16T17:04:53.994+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:04:54.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:04:54.334+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:04:54.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:05:12.265+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:05:18.301+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:05:18.247+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:05:18.582+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:05:18.581+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:05:19.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 25.751 seconds
[2025-04-16T17:05:53.874+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:05:53.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:05:53.944+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:05:53.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:12:21.433+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:12:22.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:12:30.935+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:12:26.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:13:41.476+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:13:25.809+0000] {timeout.py:68} ERROR - Process timed out, PID: 266
[2025-04-16T17:14:37.227+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:13:52.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/__init__.py", line 25, in <module>
    import pandas.compat.compressors
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 819, in module_from_spec
  File "<frozen importlib._bootstrap>", line 798, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 638, in cached
  File "<frozen importlib._bootstrap_external>", line 616, in _get_cached
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 266
[2025-04-16T17:14:48.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:23:03.879+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:23:05.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:23:06.597+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:23:06.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:23:39.714+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:23:39.632+0000] {timeout.py:68} ERROR - Process timed out, PID: 268
[2025-04-16T17:23:40.563+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:23:40.181+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/arrow/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py", line 52, in <module>
    from pandas.core.arrays._arrow_string_mixins import ArrowStringArrayMixin
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arrays/_arrow_string_mixins.py", line 11, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 336, in <module>
    _make_global_functions()
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 333, in _make_global_functions
    g[cpp_name] = g[name] = _wrap_function(name, func)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 304, in _wrap_function
    return _decorate_compute_function(wrapper, name, func, options_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 170, in _decorate_compute_function
    options_class_doc = _scrape_options_class_doc(options_class)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 117, in _scrape_options_class_doc
    doc = docscrape.NumpyDocString(options_class.__doc__)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/vendored/docscrape.py", line 151, in __init__
    self._parsed_data = copy.deepcopy(self.sections)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 118, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 268
[2025-04-16T17:23:40.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:23:42.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 44.096 seconds
[2025-04-16T17:24:14.227+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:24:14.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:24:14.275+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:24:14.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:24:31.451+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:24:42.337+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:24:42.322+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:24:42.680+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:24:42.679+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:24:43.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 29.570 seconds
[2025-04-16T17:25:17.215+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:25:17.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:25:17.243+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:25:17.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:25:37.141+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:25:40.820+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:25:40.787+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:25:41.116+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:25:41.116+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:25:41.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 24.207 seconds
[2025-04-16T17:26:12.935+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:26:12.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:26:12.999+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:26:12.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:26:27.439+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:26:27.856+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:26:27.854+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:26:28.018+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:26:28.017+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:26:28.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 15.471 seconds
[2025-04-16T17:27:20.869+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:27:21.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:27:22.184+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:27:21.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:27:35.955+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:27:36.501+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:27:36.497+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:27:36.935+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:27:36.934+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:27:37.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 28.565 seconds
[2025-04-16T17:28:08.086+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:28:08.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:28:08.106+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:28:08.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:28:19.414+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:28:20.962+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:28:20.949+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:28:24.349+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:28:24.340+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:28:24.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 16.802 seconds
[2025-04-16T17:28:56.428+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:28:56.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:28:56.808+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:28:56.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:29:12.907+0000] {processor.py:925} INFO - DAG(s) 'weather_pipeline' retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:29:14.693+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:29:14.649+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-16T17:29:15.555+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:29:15.555+0000] {dag.py:4180} INFO - Setting next_dagrun for weather_pipeline to None, run_after=None
[2025-04-16T17:29:16.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather_dag.py took 20.555 seconds
[2025-04-16T17:29:54.319+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:29:54.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:29:54.705+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:29:54.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:30:27.119+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:30:26.437+0000] {timeout.py:68} ERROR - Process timed out, PID: 371
[2025-04-16T17:30:27.679+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:30:27.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 34, in <module>
    from pandas._config import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/_config/__init__.py", line 19, in <module>
    from pandas._config import config
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/_config/config.py", line 68, in <module>
    from pandas._typing import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/_typing.py", line 245, in <module>
    class ReadBuffer(BaseBuffer, Protocol[AnyStr_co]):
                                 ~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.12/typing.py", line 395, in inner
    return _caches[func](*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/typing.py", line 1074, in _generic_class_getitem
    @_tp_cache
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 371
[2025-04-16T17:30:27.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:35:29.049+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:35:35.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:35:46.068+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:35:40.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:36:39.070+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:36:36.805+0000] {timeout.py:68} ERROR - Process timed out, PID: 380
[2025-04-16T17:37:13.214+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:36:41.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/__init__.py", line 26, in <module>
    from pandas.compat.numpy import is_numpy_dev
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/numpy/__init__.py", line 6, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/version/__init__.py", line 249, in <module>
    _legacy_version_component_re = re.compile(r"(\d+ | [a-z]+ | \.| -)", re.VERBOSE)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/__init__.py", line 228, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/_compiler.py", line 750, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/_parser.py", line 867, in _parse
    state.closegroup(group, p)
  File "/usr/local/lib/python3.12/re/_parser.py", line 98, in closegroup
    def closegroup(self, gid, p):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 380
[2025-04-16T17:37:32.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:51:18.438+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/weather_dag.py
[2025-04-16T17:51:24.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather_dag.py for tasks to queue
[2025-04-16T17:51:29.839+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:51:28.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather_dag.py
[2025-04-16T17:52:15.826+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:52:06.356+0000] {timeout.py:68} ERROR - Process timed out, PID: 382
[2025-04-16T17:52:59.592+0000] {logging_mixin.py:190} INFO - [2025-04-16T17:52:18.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/weather_dag.py", line 8, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/__init__.py", line 25, in <module>
    import pandas.compat.compressors
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/compressors.py", line 67, in <module>
    class LZMAFile(lzma.LZMAFile):
  File "<frozen abc>", line 106, in __new__
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weather_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.4/best-practices.html#reducing-dag-complexity, PID: 382
[2025-04-16T17:53:18.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather_dag.py
