[2025-02-11T23:32:25.116+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T23:32:25.148+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.load_data_to_s3 manual__2025-02-11T23:32:09.801377+00:00 [queued]>
[2025-02-11T23:32:25.164+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.load_data_to_s3 manual__2025-02-11T23:32:09.801377+00:00 [queued]>
[2025-02-11T23:32:25.166+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T23:32:25.196+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_to_s3> on 2025-02-11 23:32:09.801377+00:00
[2025-02-11T23:32:25.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T23:32:25.218+0000] {standard_task_runner.py:72} INFO - Started process 1673 to run task
[2025-02-11T23:32:25.218+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'load_data_to_s3', 'manual__2025-02-11T23:32:09.801377+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1rnnwl_j']
[2025-02-11T23:32:25.223+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask load_data_to_s3
[2025-02-11T23:32:25.326+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.load_data_to_s3 manual__2025-02-11T23:32:09.801377+00:00 [running]> on host dbef5e540f20
[2025-02-11T23:32:25.525+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aida' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='load_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T23:32:09.801377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T23:32:09.801377+00:00'
[2025-02-11T23:32:25.529+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T23:32:25.562+0000] {logging_mixin.py:190} INFO - Bucket name: weather-data-bucket
[2025-02-11T23:32:25.768+0000] {logging_mixin.py:190} INFO - File uploaded successfully to MinIO!
[2025-02-11T23:32:25.770+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T23:32:25.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T23:32:25.793+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=load_data_to_s3, run_id=manual__2025-02-11T23:32:09.801377+00:00, execution_date=20250211T233209, start_date=20250211T233225, end_date=20250211T233225
[2025-02-11T23:32:25.885+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T23:32:25.912+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
