[2025-04-16T21:23:27.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T21:23:29.873+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_to_snowflake.fetch_weather manual__2025-04-16T21:19:32.568836+00:00 [queued]>
[2025-04-16T21:23:30.181+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_to_snowflake.fetch_weather manual__2025-04-16T21:19:32.568836+00:00 [queued]>
[2025-04-16T21:23:30.225+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-16T21:23:31.670+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-04-16 21:19:32.568836+00:00
[2025-04-16T21:23:32.126+0000] {standard_task_runner.py:72} INFO - Started process 2060 to run task
[2025-04-16T21:23:32.546+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_api_to_snowflake', 'fetch_weather', 'manual__2025-04-16T21:19:32.568836+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake_pipeline.py', '--cfg-path', '/tmp/tmpwu37tv58']
[2025-04-16T21:23:32.979+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask fetch_weather
[2025-04-16T21:23:49.276+0000] {job.py:229} INFO - Heartbeat recovered after 25.22 seconds
[2025-04-16T21:23:53.495+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_api_to_snowflake.fetch_weather manual__2025-04-16T21:19:32.568836+00:00 [running]> on host b322df8cb9fb
[2025-04-16T21:26:56.675+0000] {job.py:229} INFO - Heartbeat recovered after 191.86 seconds
[2025-04-16T21:28:19.784+0000] {job.py:229} INFO - Heartbeat recovered after 90.08 seconds
[2025-04-16T21:28:23.394+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_to_snowflake' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T21:19:32.568836+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T21:19:32.568836+00:00'
[2025-04-16T21:28:24.163+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-16T21:28:51.353+0000] {job.py:229} INFO - Heartbeat recovered after 23.62 seconds
[2025-04-16T21:29:07.392+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-16T21:29:14.196+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-16T21:29:14.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_api_to_snowflake, task_id=fetch_weather, run_id=manual__2025-04-16T21:19:32.568836+00:00, execution_date=20250416T211932, start_date=20250416T212329, end_date=20250416T212914
[2025-04-16T21:29:20.890+0000] {job.py:229} INFO - Heartbeat recovered after 41.88 seconds
[2025-04-16T21:29:22.101+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T21:29:25.795+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T21:29:25.942+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-16T21:29:26.343+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
